
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

loging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: http://quote-server-dev.cfapps.io/quote

